version: '3.9'

services:
  catalog-db:
    container_name: catalog-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./docker/mongodb/data:/data/db
      - ./docker/mongodb/config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - Default

  catalog-api:
    container_name: catalog-api 
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "DatabaseStrings:ConnectionString=mongodb://admin:admin@catalog-db:27017/name?authSource=admin"
    depends_on:
      - catalog-db
    ports:
      - "8000:80"
    networks:
      - Default

networks:
  Default:
    name: microservices