version: '3.4'

services:

  catalog-db:
    image: mongo

  basket-db:
    image: redis:6.0.20-alpine

  portainer:
    image: portainer/portainer

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket-api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

