version: '3.9'

services:
  catalog-db:
    container_name: catalog-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./docker/mongodb/data:/data/db
      - ./docker/mongodb/config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - Default

  catalog-api:
    container_name: catalog-api 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseStrings:ConnectionString=mongodb://admin:admin@catalog-db:27017/name?authSource=admin"
    depends_on:
      - catalog-db
    ports:
      - "8000:80"
    networks:
      - Default
    # volumes:
      # - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
networks:
  Default:
    name: microservices
